---
# https://github.com/Azure/azure-quickstart-templates/tree/master/quickstarts/microsoft.operationsmanagement/azure-sentinel
# https://github.com/OTRF/Azure-Sentinel2Go
# https://medium.com/threat-hunters-forge/azure-sentinel-to-go-b5f6848d3c61
# https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs Sentinel = 13 matches, mostly data connector, few rules
# https://docs.ansible.com/ansible/latest/collections/azure/azcollection/index.html#plugins-in-azure-azcollection none
# https://techcommunity.microsoft.com/t5/azure-sentinel/deploying-and-managing-azure-sentinel-as-code/ba-p/1131928
# ~15min to run playbook

- name: Azure Cloud lab - Sentinel
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    base_name: azurelab0sentinel0
    base_rg: "{{ base_name }}rg"
    azure_location: eastus2
    azure_tags:
      tier: lab
      project: azure-testing
    az_object_id: "{{ lookup('env', 'AZURE_OBJECT_ID') }}"
    az_app_id: "{{ lookup('env', 'AZURE_CLIENT_ID') }}"
    az_secret: "{{ lookup('env', 'AZURE_SECRET') }}"
    az_tenant_id: "{{ lookup('env', 'AZURE_TENANT') }}"
    az_subscription_id: "{{ lookup('env', 'AZURE_SUBSCRIPTION_ID') }}"
    sentinel_workspacename: "{{ base_name }}-sentinel-workspace"
    # sentinel_userassignedidentityname: guid-app-registration
    # sentinel_arm_dir: Azure-Sentinel2Go/azure-sentinel
    # sentinel_arm_parameters: azuredeploy-az2go.parameters.json.j2
    sentinel_arm_dir: Azure-Sentinel2Go/grocery-list/Win10
    sentinel_arm_parameters: azuredeploy-az2go-win10.parameters.json.j2
    sentinel_arm_win10_admin_user: "myadmin"
    sentinel_arm_win10_admin_pass: "mypass"
    sentinel_arm_win10_allowed_ip: 192.168.1.1
    sentinel_arm_win10_num_workstations: 2
    sentinel_arm_win10_enable_sysmon: 'true'
    # Note: some c2 may block deployment when triggering security block
    sentinel_arm_win10_c2: 'None'
    sentinel_arm_win10_securitycollection: 'Minimal'

  collections:
    - azure.azcollection
  tasks:

    # General
    - name: Create resource group
      azure_rm_resourcegroup:
        name: "{{ base_rg }}"
        location: "{{ azure_location }}"
        tags: "{{ azure_tags }}"

    - name: Get Logs Analytics info
      azure_rm_resource_info:
        resource_group: "{{ base_rg }}"
        resource_type: workspaces
        provider: OperationalInsights
      register: workspaces

    # - debug: msg="{{ workspaces.response[0] }}"
    # - pause:

    - name: Create parameters
      template:
        src: "{{ sentinel_arm_parameters }}"
        dest: /tmp/azuredeploy.parameters.json
        mode: '0600'

    # App registration + contributor access on subscription
    # FIXME: AzureActivityLog data connectors not connected
    #   not idempotent
    - name: Deploy Az2go Sentinel with ARM template - az cli
      shell: az deployment group create \
        --name AnsibleDeployment \
        --resource-group {{ base_rg }} \
        --template-file azuredeploy.json \
        --parameters /tmp/azuredeploy.parameters.json
      args:
        chdir: "{{ sentinel_arm_dir }}"
      register: deploy
      when: >
        workspaces.response is not defined or workspaces.response[0].value == []

    - name: Deploy Sentinel with ARM template - az cli Output
      debug:
        msg: "{{ deploy.stdout }}"
      when: deploy is defined and deploy.stdout is defined

    - name: Get Logs Analytics info
      azure_rm_resource_info:
        resource_group: "{{ base_rg }}"
        resource_type: workspaces
        provider: OperationalInsights
      register: workspaces2

    - name: Set fact | workspaceid
      set_fact:
        workspaceid: "{{ workspaces2.response[0].properties.customerId }}"

    - debug: var=workspaceid
